from flask import Flask, render_template, jsonify, request
import random

app = Flask(__name__)

# Daftar pertanyaan random bahasa Indonesia
QUESTIONS_ID = [
    "Pernah gak sih lu ngerasa salah jurusan?",
    "Apa hal paling memalukan yang pernah lu lakuin di depan gebetan?",
    "Kalau lu bisa memutar waktu, lu mau balik ke umur berapa dan kenapa?",
    "Sebutin satu rahasia yang belum pernah lu ceritain ke siapa-siapa di sini?",
    "Siapa orang yang paling pengen lu tonjok saat ini?",
    "Menurut lu, di antara kita siapa yang bakal nikah duluan?",
    "Apa ketakutan terbesar lu yang terdengar konyol?",
    "Pernah bohong soal apa ke orang tua minggu ini?",
    "Lebih milih miskin tapi bahagia atau kaya tapi kesepian?",
    "Hal apa yang bikin lu langsung ilfeel sama orang?",
    "Mantan mana yang paling susah dilupain?",
    "Pernah nggak sih lu pura-pura sibuk main HP padahal nggak ada yang nge-chat?",
    "Apa hal terbodoh yang pernah lu lakuin demi cinta?",
    "Kalau hidup lu dibikin film, siapa aktor/aktris yang cocok meranin lu?",
    "Sebutin satu hal yang lu sesalin sampai sekarang?",
    "Siapa orang di circle ini yang paling sering ngutang tapi pura-pura lupa?",
    "Kapan terakhir kali lu nangis dan gara-gara apa?",
    "Pernah stalk IG mantan pakai fake account nggak?",
    "Kalau lu tiba-tiba dapat uang 1 milyar besok, apa yang pertama kali lu beli?",
    "Apa gosip paling aneh yang pernah lu denger tentang diri lu sendiri?",
    "Pernah ngerasa iri banget nggak sama pencapaian teman sendiri?",
    "Sebutin satu kebiasaan jorok lu yang nggak ada orang lain yang tahu?",
    "Siapa orang yang paling sering bikin lu kesal tapi tetap lu temenin?",
    "Pernah ghosting orang nggak? Kenapa?",
    "Sebutin nama orang yang lu block di WhatsApp dan alasannya?",
    "Apa hal paling nekat yang pernah lu lakuin pas lagi mabuk/ngantuk berat?",
    "Lebih milih diselingkuhin atau nyelingkuhin?",
    "Pernah naksir sama pacar teman sendiri nggak?",
    "Kalau lu cuma punya waktu hidup 24 jam lagi, lu mau ngapain?",
    "Pernah diam-diam ngebaca chat di HP pacar atau teman lu?",
    "Apa pendapat lu yang paling kontroversial tentang makanan?",
    "Menurut lu, apa sifat paling toxic yang lu punya?",
    "Siapa di antara kita yang paling gampang dibohongin?",
    "Pernah pura-pura sakit buat ngehindarin acara tongkrongan nggak?",
    "Apa pesan terakhir yang lu kirim di WhatsApp sebelum ini?",
    "Kalau disuruh hapus satu aplikasi di HP selamanya, lu bakal hapus apa?",
    "Pernah nggak sih lu ngerasa lu tuh sebenarnya orang paling pintar di circle ini?",
    "Pilih mana: nggak bisa main sosmed sebulan atau nggak bisa denger lagu sebulan?",
    "Apa aib masa kecil lu yang sampai sekarang masih sering diomongin keluarga?",
    "Siapa cinta pertama lu dan apa kabar dia sekarang?",
    "Sebutin satu hal ilegal yang pernah lu lakuin tanpa ketahuan!",
    "Kalau lu harus tukar nasib sama salah satu dari kita, lu pilih siapa?",
    "Apa pujian terbesar yang pernah lu terima tapi sebenarnya lu ngerasa nggak pantes?",
    "Pernah nggak kepikiran pengen lari dari rumah dan hilang gitu aja?",
    "Lebih milih tidur ga pake guling/bantal? Kenapa?",
    "Hal yang paling sering dipikirin pas pup?",
    "Lagu yang enak banget dinyanyiin di kamar mandi?",
    "Top playlist lagi galau?",
    "Kombo favorite kalo lagi hujan?",
    "Fakta yang kamu baru ketahui setelah karantina ini?",
    "3 rekomendasi film dari genre favorite?",
    "Pertama kali tau cara membuat bayi itu gimana?",
    "Menurut lo orang yang masih nekat mudik disaat wabah gini gimana?",
    "Hal paling gampang bikin ilfeel?",
    "Pujian paling berkesan untuk lo?",
    "Pengalaman waktu tidur di tenda pertama kali?",
    "Makanan paling enak yang pernah lo makan?",
    "Hal apa (benda) yang membuat lo rela menukar pertemanan demi mendapatkannya?",
    "Cara paling dramatis untuk bersin?",
    "Lagu yang pengen lo kasih ke orang yang lo sayang sekarang?",
    "Kalo misalnya lo punya uang 100jt untuk dibeli 3 barang, apa aja?",
    "3 permintaan dari jin lampu ajaib? (Ga boleh cinta/uang/permintaan tambahan)",
    "Jelaskan diri lo dalam 5 kata?",
    "Jelaskan penanya dalam 5 kalimat?",
    "Kalo mau punya kacamata super, pengennya bisa buat apa?",
    "1 Benda ajaib Doraemon yang pengen lo punya?",
    "Kalo bisa perjalanan waktu, hal apa yang pengen lo ubah?",
    "Kalo bisa kembali ke masa lalu buat ketemu seseorang, siapa dan ngapain?",
    "Sayuran apa yang rela lo makan seumur hidup setiap hari?",
    "Mimpi teraneh yang pernah lo pikirkan?",
    "Cara paling cepat kaya versi lo?",
    "Ngapain mainin hp terus yang ngechat juga ga ada?",
]

QUESTIONS_EN = [
    "Have you ever felt like you chose the wrong major or career path?",
    "What's the most embarrassing thing you've done in front of a crush?",
    "If you could turn back time, what age would you return to and why?",
    "Tell us one secret you've never told anyone here!",
    "Who is the person you want to punch the most right now?",
    "Who among us do you think will get married first?",
    "What is your biggest, most ridiculous fear?",
    "What did you lie to your parents about this week?",
    "Would you rather be poor but happy, or rich but lonely?",
    "What is an instant turn-off for you?",
    "Which ex is the hardest for you to forget?",
    "Have you ever pretended to be busy on your phone when no one was texting you?",
    "What is the stupidest thing you've ever done for love?",
    "If your life were a movie, who would play you?",
    "Name one thing you deeply regret to this day!",
    "Who in this circle borrows money the most but pretends to forget?",
    "When was the last time you cried and why?",
    "Have you ever stalked an ex using a fake account?",
    "If you suddenly got $1 million tomorrow, what's the first thing you'd buy?",
    "What's the weirdest rumor you've heard about yourself?",
    "If you were forced to date someone in this room, who would it be?",
    "Have you ever been extremely jealous of a friend's success?",
    "Name one gross habit you have that no one else knows about!",
    "Who annoys you the most, but you still hang out with them?",
    "Have you ever ghosted someone? Why?",
    "Name someone you blocked on WhatsApp and the reason why!",
    "What's the most reckless thing you've done while sleep-deprived or drunk?",
    "Would you rather be cheated on or be the cheater?",
    "Have you ever had a crush on a friend's partner?",
    "If you only had 24 hours left to live, what would you do?",
    "Have you ever secretly read a friend's or partner's chats?",
    "What is your most controversial opinion about food?",
    "What do you think is your most toxic trait?",
    "Who among us is the most gullible?",
    "Have you ever faked being sick to avoid hanging out?",
    "What was the last message you sent on WhatsApp before this?",
    "If you had to delete one app forever, which one would it be?",
    "Do you ever secretly think you're the smartest person in this friend group?",
    "Choose: No social media for a month, or no music for a month?",
    "What childhood embarrassment do your parents still talk about?",
    "Who was your first love, and how are they doing now?",
    "Name one illegal thing you did without getting caught!",
    "If you had to swap lives with one of us, who would you pick?",
    "What's the biggest compliment you've received that you felt you didn't deserve?",
    "Have you ever thought about running away and just disappearing?",
    "Would you rather sleep without a bolster or a pillow? Why?",
    "Tell a story about a really good friend.",
    "An unforgettable embarrassing experience.",
    "The weirdest incident in your life.",
    "Your mischief during school days.",
    "Have you ever been punished by a teacher because...",
    "Have you ever fought because...",
    "A fight you had that was actually hilarious.",
    "Getting scolded by mom but it was funny.",
    "Your weirdest behavior when you were little.",
    "A bad habit of yours.",
    "What do you miss doing?",
    "Have you ever felt like you had superpowers?",
    "The perks of being friends with you.",
    "Things you often forget.",
    "One of the luckiest things in your life.",
    "Felt wronged or disadvantaged because...",
    "You are happiest when...",
    "Hating the situation when...",
    "Feeling like disappearing from the earth out of embarrassment because...",
    "Something simple that makes you happy.",
    "Feeling strong when...",
    "Something you regretted after doing it.",
    "Favorite teacher and the reason why.",
    "The most tiring activity in your life.",
    "The most influential motivation in your life.",
    "A waste of time but fun.",
    "The most terrible anger you've seen from your parents.",
    "Something you really want to do right now.",
    "Have you ever got flustered because someone stared at you?",
    "You absolutely can't stand it when...",
    "The most tense or thrilling incident in your life.",
    "Almost died because...",
    "Your favorite activity.",
    "What do you do right after waking up?",
    "Your plans for the future.",
    "Feeling most capable in the field of...",
    "The most evil thing you've ever done.",
    "A hilarious accusation you've received.",
    "What do you like to think about?",
    "What's the thing you think about most while pooping?",
    "A really good song to sing in the bathroom?",
    "Top playlist when you're heartbroken?",
    "Favorite combo when it's raining?",
    "A fact you just found out after this quarantine?",
    "3 movie recommendations from your favorite genre?",
    "How did you first find out how babies are made?",
    "What do you think of people who are still reckless enough to go home during an outbreak like this?",
    "The easiest thing to give you the 'ick'?",
    "The most memorable compliment you've received?",
    "Have you ever brought a pacifier to school?",
    "Your first time sleeping in a tent experience?",
    "The most delicious food you've ever eaten?",
    "What object would make you willing to trade a friendship to get it?",
    "Imitate a TikTok style but without any song!",
    "The most dramatic way to sneeze?",
    "A song you want to dedicate to someone you love right now?",
    "If you had 100 million to buy 3 items, what would they be?",
    "3 wishes from a magic lamp genie? (No love, money, or extra wishes allowed)",
    "Redesign the Indonesian flag if it were colonized by Africa.",
    "Describe yourself in 5 words.",
    "Describe the asker in 5 sentences.",
    "If you could have super glasses, what would you want them to do?",
    "1 Doraemon magic gadget you want to have?",
    "If you could time travel, what would you want to change?",
    "If you could go back to the past to meet someone, who would it be and what would you do?",
    "What vegetable are you willing to eat every day for the rest of your life?",
    "The weirdest dream you've ever thought about?",
    "The fastest way to get rich according to you?",
    "Why keep playing on your phone when no one is texting you anyway?",
]


# ─── Dedicated questions for the Funny Question Spinner ───────────────────────
SPINNER_QUESTIONS = [
    "Kalo alien turun ke bumi dan minta diajarin satu tren TikTok, lu bakal ngajarin joget apa?",
    "Mending nemu bug yang bikin error se-layar, atau kode jalan lancar tapi lu nggak tau kenapa bisa jalan?",
    "Kalau lu dikasih kekuatan super tapi cuma bisa dipake buat nge-prank adek lu di rumah, kekuatan apa yang lu pilih?",
    "Lebih deg-degan mana: dapet chat \"Kita perlu ngomong\" dari pacar, atau dapet error \"Segmentation fault\" di terminal?",
    "Kalo ayam jago berkokok jam 3 pagi, itu dia lagi overthinking mikirin apa sih?",
    "Sebutin satu alasan paling absurd kenapa lu tiba-tiba ngerasa pengen ghosting orang!",
    "Lebih milih mana: Wi-Fi mati pas lagi asik push rank, atau listrik mati pas lagi main game AAA yang belum sempat di-save?",
    "Kalo ChatGPT tiba-tiba bisa ngambek dan punya perasaan, menurut lu kalimat sarkas pertama yang dia ketik ke lu apa?",
    "Menurut lu, alien kalo ke bumi bakal lebih kaget liat cowok rajin pake skincare atau liat bocil pacaran manggil 'Ayah-Bunda'?",
    "Kalau lu harus pake kostum cosplay yang absurd banget ke kampus seharian, kostum karakter apa yang lu pilih?",
    "Kalo mantan lu tiba-tiba jadi juri di kompetisi inovasi yang lu ikutin, lu bakal panik atau malah roasting dia pas presentasi?",
    "Sebutin satu kebohongan yang paling sering lu bilang ke diri sendiri pas lagi ngerjain project yang mepet deadline.",
    "Kalau karakter anime favorit lu tiba-tiba nyasar ke Banjarbaru, lu bakal ngajak dia makan apa?",
    "Hal apa yang paling sering bikin lu ngerasa 'anjir, jompo banget gue' padahal umur masih muda?",
    "Lebih milih pacar lu ngambek karena lu kelamaan main game, atau lu yang ngambek karena pacar lu jago banget main gamenya dan lu dibantai terus?",
    "Menurut lu, kenapa tutup Tupperware emak kalo ilang selalu bilangnya dicolong jin, padahal nyelip di kulkas?",
    "Mending makan seblak tapi kuahnya diganti kuah soto, atau makan soto tapi kuahnya diganti kuah seblak?",
    "Kalo lu bisa bikin satu jurusan kuliah baru yang nyeleneh banget, jurusan apa itu?",
    "Kalau lu punya 'Pintu Kemana Saja' Doraemon tapi error dan cuma bisa nganter lu ke depan minimarket, lu tetep pake nggak?",
    "Mending kelupaan bawa dompet pas lagi nongkrong, atau lupa nutup tag HTML pas lagi ngoding dan layout hancur semua?",
    "Menurut lu, debu di kamar kosan itu sebenernya spawn dari dimensi mana sih? Kerasanya cepet banget numpuknya!",
    "Kalo lu ditunjuk jadi 'Menteri Urusan Per-wibu-an', kebijakan nyeleneh apa yang bakal lu resmikan pertama kali?",
    "Kalo lu bisa ganti nama hari Senin jadi nama yang lebih vibes-nya positif, lu bakal kasih nama apa?",
    "Menurut lu, kenapa kucing oren selalu jadi tersangka utama di setiap keributan antar kucing di kompleks?",
    "Lebih panik mana: disuruh presentasi tapi lupa materi, atau salah kirim chat gibah ke dosen pembimbing?",
    "Kalo lu bisa masuk ke dunia game AAA favorit lu tapi nasib lu cuma jadi NPC yang kerjanya nyapu jalan doang, lu tetep mau nggak?",
    "Lebih anxious mana: nungguin balasan chat dari gebetan yang centang dua abu-abu, atau nunggu proses deploy website ke server?",
    "Kalo disuruh bikin skripsi tentang kelakuan Gen Z di internet, judul skripsi lu bakal kayak gimana?",
    "Seandainya di dompet lu cuma sisa Rp 15.000, lu pake buat beli es kopi susu atau mie instan pake telor?",
    "Kalo tiba-tiba ada zombie apocalypse, barang random pertama di dekat lu sekarang yang bakal lu jadiin senjata apa?",
]


@app.route("/")
def home():
    return render_template("home.html")


@app.route("/game")
def index():
    return render_template("index.html")


@app.route("/api/questions")
def get_questions():
    lang = request.args.get("lang", "id")
    questions_list = QUESTIONS_EN if lang == "en" else QUESTIONS_ID

    # Return a shuffled copy
    shuffled_questions = list(questions_list)
    random.shuffle(shuffled_questions)
    return jsonify(shuffled_questions)


@app.route("/spinner")
def spinner():
    return render_template("spinner.html")


@app.route("/api/get_question")
def get_question():
    """Returns a single randomly selected funny question from the Spinner list."""
    question = random.choice(SPINNER_QUESTIONS)
    return jsonify({"question": question})


if __name__ == "__main__":
    app.run(debug=True, port=5000)
